create table country
(
    id                  bigint generated by default as identity
        primary key,
    name                varchar(255),
    continent           varchar(255)
);

create table accommodation_users
(
    username                   varchar(255)
        primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);

create table host
(
    id                  bigint generated by default as identity
        primary key,
    name                varchar(255),
    surname             varchar(255),
    country_id          bigint references country
);

create table accommodation
(
    id                              bigint generated by default as identity
        primary key,
    name                            varchar(255),
    category                        varchar(255),
    host_id                         bigint references host,
    num_rooms                       integer,
    user_reserved_id                 varchar(255) references accommodation_users,
    user_booked_id                 varchar(255) references accommodation_users,
    is_accommodation_reserved       boolean default false,
    is_accommodation_booked         boolean default false
);

-- Removed unique
create index idx_country_name on country(name);
create index idx_accommodation_host_name on accommodation(host_id, name);
